/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'home': RouteRecordInfo<'home', '/', Record<never, never>, Record<never, never>>,
    '404': RouteRecordInfo<'404', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    'allocate': RouteRecordInfo<'allocate', '/allocate', Record<never, never>, Record<never, never>>,
    'arrive': RouteRecordInfo<'arrive', '/arrive', Record<never, never>, Record<never, never>>,
    'charts': RouteRecordInfo<'charts', '/charts', Record<never, never>, Record<never, never>>,
    'counter': RouteRecordInfo<'counter', '/counter', Record<never, never>, Record<never, never>>,
    'editarrive': RouteRecordInfo<'editarrive', '/editarrive', Record<never, never>, Record<never, never>>,
    'fix': RouteRecordInfo<'fix', '/fix', Record<never, never>, Record<never, never>>,
    'fixhistory': RouteRecordInfo<'fixhistory', '/fixhistory', Record<never, never>, Record<never, never>>,
    'fixnote': RouteRecordInfo<'fixnote', '/fixnote', Record<never, never>, Record<never, never>>,
    'KeepAlive': RouteRecordInfo<'KeepAlive', '/keepalive', Record<never, never>, Record<never, never>>,
    'library': RouteRecordInfo<'library', '/library', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'mock': RouteRecordInfo<'mock', '/mock', Record<never, never>, Record<never, never>>,
    'newoutput': RouteRecordInfo<'newoutput', '/newoutput', Record<never, never>, Record<never, never>>,
    'output': RouteRecordInfo<'output', '/output', Record<never, never>, Record<never, never>>,
    'productInfo': RouteRecordInfo<'productInfo', '/ProductInfo', Record<never, never>, Record<never, never>>,
    'productInput': RouteRecordInfo<'productInput', '/productInput', Record<never, never>, Record<never, never>>,
    '/productInput/components/AddProduct': RouteRecordInfo<'/productInput/components/AddProduct', '/productInput/components/AddProduct', Record<never, never>, Record<never, never>>,
    'productManager': RouteRecordInfo<'productManager', '/productManager', Record<never, never>, Record<never, never>>,
    'productManager/ProductInfo': RouteRecordInfo<'productManager/ProductInfo', '/productManager/components/ProductInfo', Record<never, never>, Record<never, never>>,
    'productOutput': RouteRecordInfo<'productOutput', '/productOutput', Record<never, never>, Record<never, never>>,
    'profile': RouteRecordInfo<'profile', '/profile', Record<never, never>, Record<never, never>>,
    'stockTacking': RouteRecordInfo<'stockTacking', '/stockTacking', Record<never, never>, Record<never, never>>,
    'unocss': RouteRecordInfo<'unocss', '/unocss', Record<never, never>, Record<never, never>>,
    'updatearrive': RouteRecordInfo<'updatearrive', '/updatearrive', Record<never, never>, Record<never, never>>,
  }
}
